name = input("Please enter your name:")
surname = input("Please enter your surname:")
phone_number = input("Please enter your phone number:")
street = input("Please enter your sreet name:")
house_number = input("Please enter yout house number:")
flat_number = input("Please enter your falt nomber:")
city = input("Please enter the name of your city:")
zip_code = input("Please enter your zip code:")
country = input("Please enter the name of the country you live in:")
print(name, ",", surname)
print(phone_number)
print(street, house_number,  flat_number, city,sep=", ")
print(zip_code)
print(country)
